import { Metadata } from "next";
import './global.css'

export const metadata: Metadata = {
    title: {
        // absolute: "",
        default: "Next.js", // jaha kuch nahi waha ye hai
        template: "%s | Next.js" // kuch | Next.js
    },
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="m-2">
                <header
                    style={{ backgroundColor: "lightblue", padding: "1rem" }}
                >
                    <p>Header</p>
                </header>
                {children}
                <footer style={{ backgroundColor: "pink", padding: "1rem" }}>
                    <p>Footer</p>
                </footer>
            </body>
        </html>
    );
}
